import React from 'react';

export const PrivacyPolicy: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto px-6 pt-28 pb-20 animate-fade-in-up">
      <div className="glass-panel p-8 md:p-12 rounded-3xl">
        <h1 className="text-4xl font-display font-bold text-white mb-8">Privacy Policy</h1>
        <div className="space-y-6 text-slate-300 leading-relaxed">
           <p>Last updated: {new Date().toLocaleDateString()}</p>
           <p>At StockPilotAI, accessible from stockpilotai.com, one of our main priorities is the privacy of our visitors. This Privacy Policy document contains types of information that is collected and recorded by StockPilotAI and how we use it.</p>
           
           <h2 className="text-xl font-bold text-white mt-6">Log Files</h2>
           <p>StockPilotAI follows a standard procedure of using log files. These files log visitors when they visit websites. All hosting companies do this and a part of hosting services' analytics.</p>

           <h2 className="text-xl font-bold text-white mt-6">Google Gemini API</h2>
           <p>Our application utilizes the Google Gemini API to generate content. User inputs (such as keywords and image data for metadata generation) are processed to provide the service but are not stored permanently by our application servers.</p>

           <h2 className="text-xl font-bold text-white mt-6">Local Storage</h2>
           <p>We use local storage on your browser to save your theme preference (Light/Dark mode) and saved trends. This data remains on your device.</p>
           
           <h2 className="text-xl font-bold text-white mt-6">Contact Us</h2>
           <p>If you have additional questions or require more information about our Privacy Policy, do not hesitate to contact us.</p>
        </div>
      </div>
    </div>
  );
};

export const TermsOfService: React.FC = () => {
    return (
      <div className="max-w-4xl mx-auto px-6 pt-28 pb-20 animate-fade-in-up">
        <div className="glass-panel p-8 md:p-12 rounded-3xl">
          <h1 className="text-4xl font-display font-bold text-white mb-8">Terms of Service</h1>
          <div className="space-y-6 text-slate-300 leading-relaxed">
             <p>Last updated: {new Date().toLocaleDateString()}</p>
             <p>Please read these terms and conditions carefully before using Our Service.</p>
             
             <h2 className="text-xl font-bold text-white mt-6">Interpretation and Definitions</h2>
             <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
  
             <h2 className="text-xl font-bold text-white mt-6">Acknowledgment</h2>
             <p>These are the Terms and Conditions governing the use of this Service and the agreement that operates between You and the Company. These Terms and Conditions set out the rights and obligations of all users regarding the use of the Service.</p>
  
             <h2 className="text-xl font-bold text-white mt-6">Content Generation</h2>
             <p>The content generated by this AI tool (prompts, metadata, trend analysis) is for informational and creative assistance purposes. Users are responsible for vetting the content before using it for commercial purposes on microstock platforms.</p>
             
             <h2 className="text-xl font-bold text-white mt-6">Limitation of Liability</h2>
             <p>To the maximum extent permitted by applicable law, in no event shall the Company or its suppliers be liable for any special, incidental, indirect, or consequential damages whatsoever.</p>
          </div>
        </div>
      </div>
    );
  };